### ISSUE TITLE
Update temperature question

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#10]
Update question to: "You must take and record your temperature daily. What was your temperature recording today?"

Consideration for Mike (no changes yet until we chat with Mike):
1. Do we want to change this to two separate questions:
- You must take and record your temperature daily. Were you able to take your temperature today?"
- If yes, record temperate.
- If no, "You must record your temperature daily. Learn more about how to take your temperature."... The second sentence could link to the temperature information that Marsha is planning to have uploaded. 

2. Do we want to allow users to provide a temperature in either F or C?

**Comment by gianpompilio** [comment]
@natashaminkus did we get final clarification on this?
