### ISSUE TITLE
Update support question

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#12]
Marsha provided the following content: "Is there a reason you might not be able to follow the self-isolation rules and require support for Public Health such as housing, food security, finances or Mental Health issues."

Question could be:
"Is there a reason you might not be able to follow the self-isolation rules and require support?"

Subtext could be: 
"Support could be related to housing, food, finances or mental health. For example, in some cases Nova Scotia Health can arrange transportation for COVID-19 testing for people who have no other means."

**Comment by gianpompilio** [comment]
https://gianpompilio.github.io/PNS-CDC-UI/checkin-support.html
