### ISSUE TITLE
Add daily check-in acceptance screen

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#14]
Add the following content to an acceptance screen after the questions:

Acceptance

You must confirm the following statements:

I declare that the information given on this form is complete, correct and fully discloses everything concerning my self-isolation.

I understand that it is an offence to knowingly provide false or misleading information, either orally or in writing, to a Nova Scotia Health official under the Nova Scotia Health Protection Act for which I may be fined $1000 per occurrence.

**Comment by gianpompilio** [comment]
https://gianpompilio.github.io/PNS-CDC-UI/checkin-acceptance.html
