### ISSUE TITLE
Add an isolation completion screen 

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#16]
Can we create a sample isolation complete screen and include the following content:

See attached for general formatting.

[Daily Check In_Completion_01 14 2021.docx](https://github.com/gianpompilio/PNS-CDC-UI/files/5814987/Daily.Check.In_Completion_01.14.2021.docx)

You have completed your self-isolation as of January 30, 2021 (with check mark)
You are no longer required to complete a daily check-in and no longer required to self-isolate.

What to do next

You may be contacted by Public Health
A Public Health representative may still contact you for questions about your case.

Continue to monitor for symptoms of COVID-19 
It is important to continue to monitor your health for symptoms of COVID-19. Complete a COVID-19 Self-assessment if you’re experiencing COVID-19 symptoms. You can call 811 for assessment if you’re unable to complete the COVID-19 Self-assessment online (or to speak with a nurse).

Stay diligent and safe
In addition to getting the vaccine, you need to follow public health directives, including gathering limits, social distancing guidelines, hand washing guidelines and wearing a mask when in public places. You should also stay home if you feel unwell and complete a COVID-19 Self-assessment.

**Comment by gianpompilio** [comment]
https://gianpompilio.github.io/PNS-CDC-UI/completion.html
