### ISSUE TITLE
Changes to registration form

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#3]
Changes to registration form:

- Calendar picker (Mike to confirm)
- Register button should be green
- Sentence case for field names (e.g., email address)
- Remove "I consent to share my data."
- Update to Health Card Number
- Add subtext to say "As directed by Public Health and can be found registration email."

**Comment by gianpompilio** [comment]
@natashaminkus Should that subtext replace what's there?  Is it clear enough on its own? 

I still have to update the calendar.

**Comment by natashaminkus** [comment]
Sorry, I should've been clearer. 

- You can remove the subtext at the top 
- Add subtext below the Isolation end date field to say:  Enter the isolation end date provided to you by Public Health.

![image](https://user-images.githubusercontent.com/77400929/105188959-d538c480-5b0a-11eb-9f49-f7296b96d8b0.png)
