### ISSUE TITLE
Update title

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#7]
Update title to "COVID-19 Daily Check-In".

Based on existing content, CNS prefers COVID-19 over Covid/COVID.

**Comment by gianpompilio** [comment]
Ran this script to update all instances of "Covid Daily Check-in" to "COVID-19 Daily Check-In" in html files within the repo.

`perl -pi -w -e 's/Covid Daily Check-in/COVID-19 Daily Check-In/g;' ~/PNS/Apps/CDC-UI/*.html`
