### ISSUE TITLE
Update "Have you been able to continue your self isolation?" content

### ISSUE THREAD

**Issue by natashaminkus** [gianpompilio/PNS-CDC-UI#8]
Update to "Are you still self-isolating at your home or place of stay?" to align with content in Safe Check In.

"self-isolate" should hyperlink to: https://novascotia.ca/coronavirus/symptoms-and-testing/?&_ga=2.124340169.2101808046.1610464792-133069749.1599043171#self-isolate

**Comment by gianpompilio** [comment]
https://gianpompilio.github.io/PNS-CDC-UI/checkin-isolating.html
